name: android lint and ktlintCheck

on: [ push ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.12

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/android/.gradle/caches
            ~/android/.gradle/wrapper
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-cache-

      - name: Android Lint and Ktlint Check
        run: cd ./android && ./gradlew clean lint ktlintCheck --continue
