name: Main

on: [ push, pull_request ]

env:
  working-directory: android

jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.working-directory}}

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.12

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/${{env.working-directory}}/.gradle/caches
            ~/${{env.working-directory}}/.gradle/wrapper
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-cache-
      
      - name: Clean Project
        run: ./gradlew clean

      - name: Android Lint
        run: ./gradlew lint --continue

      - name: Code Style Check
        run: ./gradlew detekt --continue
      
      - name: Unit Test
        run: ./gradlew test --continue
