name: Main

on: [ push, pull_request ]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 11 for Gradle
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.12

      - name: Clean Project
        run: ./gradlew clean

      - name: Check Code Style
        run: ./gradlew checkCodeStyle

      - name: Build & Test
        run: ./gradlew test
